### ISSUE TITLE
Translation using doGet() fails

### ISSUE THREAD

**Issue by dstillman** [adomasven/translation-server-node-v2#1]
Trying to translate https://www.worldcat.org/title/test/oclc/917189063&referer=brief_results

```
ReferenceError: xmlhttp is not defined

    ReferenceError: xmlhttp is not defined
        at Zotero.Utilities.Translate.doGet (/Users/dan/translation-server-node-v2/src/utilities_translate.js:335:37)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:118:7)
```

**Comment by adomasven** [comment]
Force pushed and fixed
